# Generated by Django 4.2.30 on 2026-10-05 00:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código / referencia')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KILOGRAMO', 'Kilogramo'), ('GRAMO', 'Gramo'), ('LITRO', 'Litro'), ('MILILITRO', 'Mililitro'), ('METRO', 'Metro'), ('CAJA', 'Caja'), ('SERVICIO', 'Servicio')], default='UNIDAD', max_length=20, verbose_name='unidad')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tasa aplicable (p. ej. 19.00 para un IVA del 19%). La codificación tributaria específica de DIAN/Factus (tipo de impuesto, código) se definirá en la fase de Facturación.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='porcentaje de impuesto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresa.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_producto_codigo_por_empresa'),
        ),
    ]
