# Generated by Django 4.2.30 on 2026-10-05 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PASAPORTE', 'Pasaporte')], default='CC', max_length=20, verbose_name='tipo de identificación')),
                ('numero_identificacion', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La identificación debe tener entre 3 y 20 caracteres alfanuméricos.', regex='^[A-Za-z0-9-]{3,20}$')], verbose_name='número de identificación')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre / razón social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresa.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_identificacion', 'numero_identificacion'), name='unique_cliente_identificacion_por_empresa'),
        ),
    ]
