# Generated by Django 4.2.30 on 2026-10-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa (tenant) a la que pertenece el usuario. Vacío únicamente para administradores de plataforma (is_superuser=True).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='empresa.empresa', verbose_name='empresa'),
        ),
    ]
