# Generated by Django 4.2.30 on 2026-10-04 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='razón social')),
                ('tipo_identificacion', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte')], default='NIT', max_length=20, verbose_name='tipo de identificación')),
                ('numero_identificacion', models.CharField(help_text='Identificación tributaria de la empresa (NIT u otro documento válido).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La identificación debe contener únicamente números (5 a 20 dígitos).', regex='^\\d{5,20}$')], verbose_name='número de identificación')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('municipio', models.CharField(blank=True, max_length=150, verbose_name='municipio / ciudad')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
